// <auto-generated />
using System;
using BackendNetCore.T24ApiNetCore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BackendNetCore.T24ApiNetCore.Migrations
{
    [DbContext(typeof(T24Context))]
    [Migration("20210530170753_AddForeingKey")]
    partial class AddForeingKey
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("BackendNetCore.T24ApiNetCore.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Apellido")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<int?>("DNI")
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("datetime");

                    b.Property<string>("Nombre")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("BackendNetCore.T24ApiNetCore.Models.AsignadoA", b =>
                {
                    b.Property<string>("ProyectoId")
                        .HasColumnType("varchar(4)");

                    b.Property<string>("CientificoId")
                        .HasColumnType("varchar(8)");

                    b.HasKey("ProyectoId", "CientificoId");

                    b.HasIndex("CientificoId");

                    b.ToTable("AsignadoAs");
                });

            modelBuilder.Entity("BackendNetCore.T24ApiNetCore.Models.Cientifico", b =>
                {
                    b.Property<string>("DNI")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<string>("NombreCompleto")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("DNI");

                    b.ToTable("Cientificos");
                });

            modelBuilder.Entity("BackendNetCore.T24ApiNetCore.Models.Proyecto", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)");

                    b.Property<int>("Horas")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Proyectos");
                });

            modelBuilder.Entity("BackendNetCore.T24ApiNetCore.Video", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("Director")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Title")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("BackendNetCore.T24ApiNetCore.Models.AsignadoA", b =>
                {
                    b.HasOne("BackendNetCore.T24ApiNetCore.Models.Cientifico", "Cientifico")
                        .WithMany("AsignadoAs")
                        .HasForeignKey("CientificoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendNetCore.T24ApiNetCore.Models.Proyecto", "Proyecto")
                        .WithMany("AsignadoAs")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cientifico");

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("BackendNetCore.T24ApiNetCore.Video", b =>
                {
                    b.HasOne("BackendNetCore.T24ApiNetCore.Cliente", "Cliente")
                        .WithMany("Videos")
                        .HasForeignKey("ClienteId");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("BackendNetCore.T24ApiNetCore.Cliente", b =>
                {
                    b.Navigation("Videos");
                });

            modelBuilder.Entity("BackendNetCore.T24ApiNetCore.Models.Cientifico", b =>
                {
                    b.Navigation("AsignadoAs");
                });

            modelBuilder.Entity("BackendNetCore.T24ApiNetCore.Models.Proyecto", b =>
                {
                    b.Navigation("AsignadoAs");
                });
#pragma warning restore 612, 618
        }
    }
}
